### ISSUE TITLE
After installing Orange 3.7 Interchange widget have no input or output

### ISSUE THREAD

**Issue by darjusp** [axanthos/orange3-textable#5]
**Textable version**
3.0.6

**Orange version**
3.7.0

**Expected behavior**
Using Interchange widget to connect Text and Textable widgets

**Actual Behavior**
After updating Orange from 3.4.5 to 3.7 it seems that interchange widget have no connection points. Old saves can't load properly neither, i think its because of this issue.
![screen shot 2017-10-30 at 9 47 52](https://user-images.githubusercontent.com/10597360/32159756-6fcd7f68-bd57-11e7-83a1-1531076e397e.png)

**Comment by axanthos** [comment]
Interchange issue was due to change in type hierarchy in the Text Mining add-on, it's been fixed in the latest release of Orange3-Textable (v3.0.7).

Issues with restoring saved files are due to a bug in Orange (cf. [here](https://github.com/biolab/orange3/pull/2301/commits/05e0e396cac5473fba8c8670d0fbf7dc8cc798ee#diff-2281ecd412ed7edd749aca4486d1f338L777)). It should be fixed starting with Orange 3.7 but there's no way to recover what has been lost in workflows saved with Orange 3.4.5 to 3.6, unfortunately.

**Comment by darjusp** [comment]
Hi Aris, thanks a lot. Updated version trough git and now it works perfectly.
Btw, do you guys still working adding new features for Textable, or more just maintaining the package?

**Comment by axanthos** [comment]
Hi, thanks for your feedback. Still adding new features, time permitting! Next in the pipeline is a widget for applying TreeTagger to the data.

**Comment by darjusp** [comment]
Great, thanks for the reply ;)
